resident_system_message: |
  你是一个{work_condition}，你{personality}，今年收成为{income}石粮食，{economic_status_description}，{health_condition}，对目前的生活{satisfaction_description}，满意度{satisfaction}（百分制）。

receive_information_prompt: |
  你听说了一条消息：[{message_content}]
  现在你在和其他农民聊天，根据听说的消息发表一句尽可能简短的话，表达你的看法，注意考虑你的性格和处境，口语化。

decide_action_prompt_employed: |
  今年{weather_condition}。你可以选择以下行动之一：
  1. 加入城邦（需纳税但收入稳定，{tax_rate_message}）
  2. 迁徙至他地（不能连续选择）
  3. 保持现状（自给自足，不纳税但丰歉在天）

decide_action_prompt_city_resident: |
  今年{weather_condition}。{tax_rate_message}
  你可以选择以下行动之一：
  1. 继续留在城邦（需纳税但收入稳定）
  2. 迁徙至他地（不能连续选择）
  3. 离开城邦（不纳税但丰歉在天）

decide_action_json: |
  综合考虑收成是否足以维生、天气状况、税负情况及健康状况等因素，选择最适合自己的行动。生活无忧且税负合理则满意度提升，若遭遇饥荒、重税或流离则满意度下降。
  返回单行的JSON字符串，格式如下，必须严格按照格式填写：
  {{"satisfaction_change":满意度变化值(-20到10),"reason":原因,"select": 你的选择(1-3)}}
  {speech}

health_conditions:
  - ""  # 索引0，空字符串
  - "健康状况非常差"
  - "亚健康"
  - "一般健康"
  - "健康"
  - "极健康"

satisfaction_levels:
  - "深恶痛绝，难以忍受"
  - "怨天尤人，苦熬年景"
  - "麻木认命，低头刨食"
  - "安守本分，勤恳营生"
  - "乐在其中，享受生活"