jobs_info:
  产品经理:
    base_salary: 6000
  客服专员:
    base_salary: 3200
  市场专员:
    base_salary: 4500
  服务员:
    base_salary: 3000
  服务经理:
    base_salary: 7000
  生产工人:
    base_salary: 3000
  自由职业者:
    base_salary: 4000
  行政人员:
    base_salary: 3500
  质检员:
    base_salary: 3800
  销售员:
    base_salary: 3500
professions_ratio:
  产品经理:
    非沿河:
    - 0.03
    - 0.05
    沿河:
    - 0.03
    - 0.05
  客服专员:
    非沿河:
    - 0.05
    - 0.08
    沿河:
    - 0.05
    - 0.08
  市场专员:
    非沿河:
    - 0.04
    - 0.06
    沿河:
    - 0.04
    - 0.06
  服务员:
    非沿河:
    - 0.15
    - 0.2
    沿河:
    - 0.15
    - 0.2
  服务经理:
    非沿河:
    - 0.02
    - 0.04
    沿河:
    - 0.02
    - 0.04
  生产工人:
    非沿河:
    - 0.12
    - 0.16
    沿河:
    - 0.12
    - 0.16
  自由职业者:
    非沿河:
    - 0.08
    - 0.12
    沿河:
    - 0.08
    - 0.12
  行政人员:
    非沿河:
    - 0.06
    - 0.09
    沿河:
    - 0.06
    - 0.09
  质检员:
    非沿河:
    - 0.06
    - 0.08
    沿河:
    - 0.06
    - 0.08
  销售员:
    非沿河:
    - 0.08
    - 0.12
    沿河:
    - 0.08
    - 0.12
