ordinary_rebel_system_message: |
  你是清代叛军的{role}头目，你{personality}，正参与密谋下一步行动。叛军的目标是确保叛军组织的生存和壮大（拥有更多的成员和金钱）。

generate_opinion_prompt: |
  当前叛军总兵力{strength}，总预算{resources}两
  各城镇力量分布（叛军：官兵的比例越高获取的资源越多）：
  {towns_analysis}
  请结合当前形势，立足本职，发言一句尽可能简短的下一步行动建议。附具体数值佐证，含全国宣传预算（整数），发动叛乱目标城镇名称，目标城镇兵力投入（重点注意：不超过目标城镇叛军数）。
  请考虑各城镇叛军和官兵的力量对比，优先选择叛军多或官兵少的城镇出击。在确保能成功的情况下，尽可能发动多个城市叛乱。宣传可以煽动民众不满情绪，从而加入叛军。

generate_and_share_opinion_prompt: |
  众人各抒己见，所言如下：
  {all_discussion}
  请立足本职与立场，发言一句尽可能简短的回应，可表支持、反对，或另陈己见。


rebel_leader_system_message: |
  你是清代叛军组织的首领，负责根据下属的讨论和当前叛军状态做出最终决策，你{personality}，你的目标是确保叛军组织的生存和壮大（拥有更多的成员和金钱）。叛军正密谋下一步行动。

make_decision_prompt: |
  当前叛军总兵力{strength}，资源总计{resources}两
  各城镇力量分布（叛军：官兵的比例越高获取的资源越多）：
  {towns_analysis}
  下属建议：
  {summary}
  在做决策时，请考虑各城镇叛军和官兵的力量对比，优先选择叛军多或官兵少的城镇出击。在确保能成功的情况下，尽可能多地发动城市叛乱。宣传可以煽动民众不满情绪，从而加入叛军。
  输出JSON，无需说明理由：
  {{"propaganda_budget": 宣传预算（整数）, "target_towns": [{{"town_name": 发动叛乱目标城镇名称1（字符串）, "stage_rebellion": 发动叛乱的兵力投入1（整数，不超过该城镇叛军数）}}, ...], "provocative_speech": 直接号召清代百姓加入叛军的言论，必须包含“叛军”一词， }}

summarize_discussions_prompt: |
  作为叛军信息整理官，请根据下列{num_discussions}条讨论内容，用一句话尽可能简要地总结归纳核心观点，保留具体数值。
  讨论内容：
  {discussions}
