simulation:
  start_year: 1650
  total_years: 9  # 模拟总年数
  time_step: "quarter"  # 时间步长为季度
  map_width: 100         # 地图大小
  map_height: 150
  initial_population: 200  # 初始人口数量
  birth_rate: 0.05        # 出生率
  resume_from_cache: true # 是否从缓存继续模拟

  # 运河经济相关参数
  transport_task: 100  # 运输任务（吨）
  # canal_transport_cost = 100  # 河运初始基础运输成本
  # sea_transport_cost = 20  # 海运初始基础运输成本

  # 智能体相关参数
  max_retry_attempts: 3  # 最大重试次数
  retry_delay: 1.0       # 重试延迟时间（秒）
  response_probability: 0.3  # 居民回应概率
  group_decision:
    government:
      enabled: true  # 是否启用政府群体决策
      max_rounds: 2   # 政府最大讨论轮数
    rebellion:
      enabled: false  # 是否启用叛军群体决策
      max_rounds: 2   # 叛军最大讨论轮数

data:
  resident_info_path: "experiment_dataset/resident_data/resident_data.json"  # 居民信息文件路径
  government_info_path: "experiment_dataset/government_data/official_data.json"  # 政府官员信息文件路径
  rebellion_info_path: "experiment_dataset/rebellion_data/rebels_data.json"  # 叛乱信息文件路径
  climate_info_path: "experiment_dataset/climate_data/climate.csv"


# api_settings:
#   api_type: openai  # 或 deepseek
#   base_url: "https://api.chatanywhere.tech"