data:
  jobs_config_path: config_info_propagation/jobs_config.yaml
  message_config_path: config_info_propagation/message_config.yaml
  questionnaire_path: config_info_propagation/questionnaire.yaml
  resident_info_path: experiment_dataset/resident_data/resident_data.json
  resident_prompt_path: config_info_propagation/residents_prompts.yaml
  towns_data_path: config_info_propagation/towns_data.json
simulation:
  birth_rate: 0.05
  initial_population: 3
  map_height: 100
  map_width: 100
  max_retry_attempts: 3
  message_type: L
  response_probability: 0.2
  retry_delay: 1
  seed_count: 1
  start_year: 2016
  total_years: 1
