simulation:
  # 基本配置
  map_width: 100
  map_height: 100
  start_year: 2016
  total_years: 3
  initial_population: 20 #初始人口数量
  birth_rate: 0.05
  seed_count: 5      # 种子数量

  # 智能体相关参数
  max_retry_attempts: 3  # 最大重试次数
  retry_delay: 1.0       # 重试延迟时间（秒）
  response_probability: 0.2  # 居民回应概率

  message_type: L    #信息类型（S:短信息，L:长信息）


# 数据文件路径
data:
  towns_data_path: "config_info_propagation/towns_data.json"
  resident_info_path: "experiment_dataset/resident_data/resident_data.json"
  resident_prompt_path: "config_info_propagation/residents_prompts.yaml"
  jobs_config_path: "config_info_propagation/jobs_config.yaml"
  message_config_path: "config_info_propagation/message_config.yaml"
  questionnaire_path: "config_info_propagation/questionnaire.yaml"
