jobs_info:
  交易员:
    base_salary: 6000
  基金经理:
    base_salary: 10000
  散户投资者:
    base_salary: 3000
  机构投资者:
    base_salary: 8000
  金融分析师:
    base_salary: 7000
  趋势投资者:
    base_salary: 5000
professions_ratio:
  交易员:
    沿河:
    - 0.2
    - 0.3
    非沿河:
    - 0.15
    - 0.25
  基金经理:
    沿河:
    - 0.05
    - 0.12
    非沿河:
    - 0.03
    - 0.08
  散户投资者:
    沿河:
    - 0.45
    - 0.6
    非沿河:
    - 0.5
    - 0.65
  机构投资者:
    沿河:
    - 0.08
    - 0.15
    非沿河:
    - 0.05
    - 0.1
  金融分析师:
    沿河:
    - 0.08
    - 0.15
    非沿河:
    - 0.05
    - 0.1
  趋势投资者:
    沿河:
    - 0.1
    - 0.2
    非沿河:
    - 0.08
    - 0.15

