jobs_info:
  个人投资者:
    base_salary: 4000
  交易所管理员:
    base_salary: 10000
  做市商:
    base_salary: 8000
  市场分析师:
    base_salary: 7000
  机构投资者:
    base_salary: 12000
  监管人员:
    base_salary: 9000
professions_ratio:
  个人投资者:
    交易所A:
    - 0.45
    - 0.55
    交易所B:
    - 0.5
    - 0.6
    沿河:
    - 0.45
    - 0.55
    非沿河:
    - 0.5
    - 0.6
  交易所管理员:
    交易所A:
    - 0.03
    - 0.05
    交易所B:
    - 0.03
    - 0.05
    沿河:
    - 0.03
    - 0.05
    非沿河:
    - 0.03
    - 0.05
  做市商:
    交易所A:
    - 0.05
    - 0.08
    交易所B:
    - 0.04
    - 0.07
    沿河:
    - 0.05
    - 0.08
    非沿河:
    - 0.04
    - 0.07
  市场分析师:
    交易所A:
    - 0.08
    - 0.12
    交易所B:
    - 0.06
    - 0.1
    沿河:
    - 0.08
    - 0.12
    非沿河:
    - 0.06
    - 0.1
  机构投资者:
    交易所A:
    - 0.15
    - 0.2
    交易所B:
    - 0.1
    - 0.15
    沿河:
    - 0.15
    - 0.2
    非沿河:
    - 0.1
    - 0.15
  监管人员:
    交易所A:
    - 0.04
    - 0.06
    交易所B:
    - 0.04
    - 0.06
    沿河:
    - 0.04
    - 0.06
    非沿河:
    - 0.04
    - 0.06
